### ISSUE TITLE
Creating and inserting a <br> element produces a </br> end tag

### ISSUE THREAD

**Issue by forbjok** [eBookingServices/htmld#36]
... but `<br>` is not supposed to have an end tag.

This bug appears to have been introduced in v0.3.5.
In v0.3.4 it produces a simple `<br>` with no end tag, as expected.

Minimal reproduction of the issue here: https://github.com/forbjok/htmld-repro

**Comment by marcioapm** [comment]
Fixed by d2a693c81fd8d5e8b8efaa328743ef0a0ddf805b
